import type { Enum } from '@/types/enum';

export const KEY_CODES = {
  ENTER: 'Enter',
  DELETE: 'Delete',
  TAB: 'Tab',
  ESCAPE: 'Escape',
  SPACE: ' ',
  BACKSPACE: 'Backspace',
  MINUS: '-',
  PLUS: '+',
  MULTIPLY: '*',
  DIVIDE: '/',
  LEFT: 'ArrowLeft',
  RIGHT: 'ArrowRight',
  UP: 'ArrowUp',
  DOWN: 'ArrowDown',
  PERIOD: 'Period',
  SLASH: '/',
  DECIMAL: '.',
  COMMA: ',',
  A: 'a',
  B: 'b',
  C: 'c',
  D: 'd',
  E: 'e',
  F: 'f',
  G: 'g',
  H: 'h',
  I: 'i',
  J: 'j',
  K: 'k',
  L: 'l',
  M: 'm',
  N: 'n',
  O: 'o',
  P: 'p',
  Q: 'q',
  R: 'r',
  S: 's',
  T: 't',
  U: 'u',
  V: 'v',
  W: 'w',
  X: 'x',
  Y: 'y',
  Z: 'z',
  ZERO: '0',
  ONE: '1',
  TWO: '2',
  THREE: '3',
  FOUR: '4',
  FIVE: '5',
  SIX: '6',
  SEVEN: '7',
  EIGHT: '8',
  NINE: '9',
  BACKSLASH: '\\',
  BRACKET_LEFT: '[',
  BRACKET_RIGHT: ']',
  QUOTE: "'",
  SEMICOLON: ';',
  EQUALS: '=',
  SHIFT: 'Shift',
  CONTROL: 'Control',
  ALT: 'Alt',
} as const;

export type KeyCode = Enum<typeof KEY_CODES>;
